apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/karthik-jk-tenant/dc-metro-map/dc-metro-map@sha256:f22c378fa17895511559fed15a69837678b779c855424ded335755ee6c142559
        name: container-image
        resources: {}
status: {}
